### ISSUE TITLE
Export Classes in inline_dialogs.dart

### ISSUE THREAD

**Issue by defuncart** [1SouravGhosh/flutter_inline_dialogs#3]
`DialogManager`, `DialogService`, and `DialogType`, `DialogRequest` and `DialogResponse` should be exported in `inline_dialogs.dart`.

This would then result in the following import

```dart
import 'package:inline_dialogs/inline_dialogs.dart'
```

instead of importing members directly from the package

```dart
import 'package:inline_dialogs/dialogs/manager.dart';
```

which can raise `implementation_imports` linter warning.

Also, all source code could be placed in `lib/src`.

@1SouravGhosh I am happy to put together a solution if you like.

**Comment by 1SouravGhosh** [comment]
Sure, Please go ahead.
